# Generated by Django 4.2.4 on 2023-08-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceOfferings', models.CharField(blank=True, max_length=10000)),
            ],
        ),
    ]
