# Generated by Django 4.2.4 on 2023-08-27 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_api', '0001_initial'),
        ('home_api', '0002_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization_api.organization'),
        ),
    ]
