# Generated by Django 4.2.4 on 2023-08-27 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_api', '0003_alter_events_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
