# Generated by Django 4.2.4 on 2023-08-23 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('develop_typed', models.CharField(blank=True, max_length=655)),
                ('dob', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('work_exp_year', models.CharField(blank=True, max_length=625)),
                ('work_exp_work', models.CharField(blank=True, max_length=625)),
                ('educated_year', models.CharField(blank=True, max_length=625)),
                ('educated_university', models.CharField(blank=True, max_length=625)),
                ('skill', models.CharField(blank=True, max_length=625)),
                ('instagram', models.CharField(blank=True, max_length=225)),
                ('twitter', models.CharField(blank=True, max_length=225)),
                ('github', models.CharField(blank=True, max_length=225)),
                ('codepen', models.CharField(blank=True, max_length=225)),
                ('youtube', models.CharField(blank=True, max_length=225)),
                ('facebook', models.CharField(blank=True, max_length=225)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
