# Generated by Django 4.2.4 on 2023-08-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='develop_typed',
            field=models.CharField(blank=True, default='[]', max_length=655),
        ),
        migrations.AlterField(
            model_name='profile',
            name='educated_university',
            field=models.CharField(blank=True, default='[]', max_length=625),
        ),
        migrations.AlterField(
            model_name='profile',
            name='educated_year',
            field=models.CharField(blank=True, default='[]', max_length=625),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skill',
            field=models.CharField(blank=True, default='[]', max_length=625),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_exp_work',
            field=models.CharField(blank=True, default='[]', max_length=625),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_exp_year',
            field=models.CharField(blank=True, default='[]', max_length=625),
        ),
    ]
