# Generated by Django 4.2.4 on 2023-08-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0003_projectimage_alter_profile_image_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='user',
        ),
        migrations.AddField(
            model_name='projects',
            name='user',
            field=models.ManyToManyField(to='profile_api.profile'),
        ),
    ]
