# Generated by Django 4.2.4 on 2023-08-24 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0004_remove_projects_user_projects_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='projects_works',
            field=models.ManyToManyField(blank=True, to='profile_api.projects'),
        ),
        migrations.RemoveField(
            model_name='projects',
            name='user',
        ),
        migrations.AddField(
            model_name='projects',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profile_api.profile'),
            preserve_default=False,
        ),
    ]
