# Generated by Django 4.2.4 on 2023-08-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0005_profile_projects_works_remove_projects_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='user',
        ),
        migrations.AlterField(
            model_name='projects',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='profile_api.projectimage'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
