# Generated by Django 4.2.4 on 2023-08-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0006_remove_projects_user_alter_projects_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='images',
            field=models.ImageField(blank=True, upload_to='images\\profile\\projects'),
        ),
    ]
