# Generated by Django 4.2.4 on 2023-08-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0008_rename_images_projectimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='LinkedIn',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
