# Generated by Django 4.2.4 on 2023-08-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2555)),
                ('startDate', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='events',
            field=models.ManyToManyField(to='organization_api.events'),
        ),
    ]
