# Generated by Django 4.2.4 on 2023-08-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_api', '0002_events_organization_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='eventType',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
