# Generated by Django 4.2.4 on 2023-08-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_api', '0003_events_eventtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='events',
            field=models.ManyToManyField(related_name='organization', to='organization_api.events'),
        ),
    ]
