# Generated by Django 4.2.4 on 2023-08-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_api', '0004_alter_organization_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='applications',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='events',
            name='content',
            field=models.CharField(blank=True, max_length=2555),
        ),
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, upload_to='organization/events'),
        ),
        migrations.AddField(
            model_name='organization',
            name='image',
            field=models.ImageField(blank=True, upload_to='organization'),
        ),
    ]
