# Generated by Django 4.2.4 on 2023-09-03 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_api', '0005_events_applications_events_content_events_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentsDataFile', models.FileField(blank=True, upload_to='organization/dataFiles')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization_api.organization')),
            ],
        ),
    ]
